### Create New User
POST https://nodeapijs.azurewebsites.net/api/auth/register
Content-Type: application/json
 
{ 
    "username": "muratvuranok2", 
    "password": "Pro247!!" ,
    "firstname":"murat",
    "lastname":"vuranok",
    "email":"muratvuranok@hotmail.com"
}
 

### Login

POST https://nodeapijs.azurewebsites.net/api/auth/login
Content-Type: application/json
 
{ 
    "username": "muratvuranok", 
    "password": "Pro247!!" 
}  