import { createAsyncThunk } from '@reduxjs/toolkit'
import { UserState } from './types'
import { UserService } from '../../network/services/UserService'
import User from '../../network/models/User'
import createBaseSlice from '../../network/reducers/core/BaseSlice'
